server:
  port: 10010

spring:
  application:
    name: study-zuul


zuul:
  routes:
    study-provider: /provider/**
    study-consumer: /consumer/**
  prefix: /api

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka

