server:
  port: 8082

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///ssm01
    username: root
    password: root
  application:
    name: study-provider    #将来作为微服务的名称

mybatis:
  type-aliases-package: com.gu.pojo
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    # register-with-eureka: true    服务提供方启动时，会检测该参数是否为true，true-注册给eureka  默认true
  instance:
    lease-renewal-interval-in-seconds: 5    #心跳时间 5s一次心跳
    lease-expiration-duration-in-seconds: 15    #过期时间 15s就过期
